2024-11-22 16:25:59 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://10.140.54.124:20001', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False, debug=False, with_debug_parameter=False)
2024-11-22 16:25:59 | INFO | gradio_web_server | Models: ['grounding_dino']
2024-11-22 16:25:59 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://10.140.54.124:20001', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False, debug=False, with_debug_parameter=False)
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_1
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_2
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_3
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_4
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_5
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_6
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_7
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | ERROR | stderr | /mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_8
2024-11-22 16:26:17 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2024-11-22 16:26:17 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2024-11-22 16:26:17 | INFO | stdout | 
2024-11-22 16:26:17 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2024-11-22 16:26:25 | INFO | gradio_web_server | load_demo. ip: 10.1.10.18
2024-11-22 16:26:25 | INFO | gradio_web_server | Models: ['grounding_dino']
2024-11-22 16:27:03 | INFO | gradio_web_server | add_text. ip: 10.1.10.18. len: 5
2024-11-22 16:27:04 | INFO | gradio_web_server | http_bot. ip: 10.1.10.18
2024-11-22 16:27:04 | INFO | stdout | template_name:  vicuna_v1
2024-11-22 16:27:04 | INFO | stdout | Messages： [['USER', ('train\n<image>', <PIL.Image.Image image mode=RGB size=3886x2591 at 0x7F9364C3E920>, 'Crop', <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=3886x2591 at 0x7F9364C3EB90>)], ['ASSISTANT', None]]
2024-11-22 16:27:04 | INFO | gradio_web_server | model_name: grounding_dino, worker_addr: http://localhost:20003
2024-11-22 16:27:04 | INFO | gradio_web_server | ==== request ====
{'model': 'grounding_dino', 'prompt': "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\ntrain ASSISTANT:", 'temperature': 0.2, 'top_p': 0.7, 'max_new_tokens': 512, 'stop': '</s>', 'images': "List of 1 images: ['a9b99b18f2d7176e88f73b89f641b5e1']"}
==== request ====
2024-11-22 16:27:04 | ERROR | stderr | Traceback (most recent call last):
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
2024-11-22 16:27:04 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
2024-11-22 16:27:04 | ERROR | stderr |     result = await self.call_function(
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
2024-11-22 16:27:04 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
2024-11-22 16:27:04 | ERROR | stderr |     return await iterator.__anext__()
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
2024-11-22 16:27:04 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-11-22 16:27:04 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024-11-22 16:27:04 | ERROR | stderr |     return await future
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024-11-22 16:27:04 | ERROR | stderr |     result = context.run(func, *args)
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
2024-11-22 16:27:04 | ERROR | stderr |     return next(iterator)
2024-11-22 16:27:04 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/code/reasoning/tool-agent/LLaVA-Plus-Codebase/llava/serve/gradio_web_server_llava_plus.py", line 468, in http_bot
2024-11-22 16:27:04 | ERROR | stderr |     if data["error_code"] == 0:
2024-11-22 16:27:04 | ERROR | stderr | KeyError: 'error_code'
2024-11-22 16:44:58 | INFO | gradio_web_server | load_demo. ip: 10.1.10.19
2024-11-22 16:44:58 | INFO | gradio_web_server | Models: ['grounding_dino']
2024-11-22 16:45:15 | INFO | gradio_web_server | add_text. ip: 10.1.10.19. len: 3
2024-11-22 16:45:15 | INFO | gradio_web_server | http_bot. ip: 10.1.10.19
2024-11-22 16:45:15 | INFO | stdout | template_name:  vicuna_v1
2024-11-22 16:45:15 | INFO | stdout | Messages： [['USER', ('dot\n<image>', <PIL.Image.Image image mode=RGB size=800x557 at 0x7F9364C3C880>, 'Crop', <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=800x557 at 0x7F9364C3DC90>)], ['ASSISTANT', None]]
2024-11-22 16:45:15 | INFO | gradio_web_server | model_name: grounding_dino, worker_addr: http://localhost:20003
2024-11-22 16:45:15 | INFO | gradio_web_server | ==== request ====
{'model': 'grounding_dino', 'prompt': "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\ndot ASSISTANT:", 'temperature': 0.2, 'top_p': 0.7, 'max_new_tokens': 512, 'stop': '</s>', 'images': "List of 1 images: ['7b81764077ee3ff93f2fe5bebf579598']"}
==== request ====
2024-11-22 16:45:15 | ERROR | stderr | Traceback (most recent call last):
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
2024-11-22 16:45:15 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
2024-11-22 16:45:15 | ERROR | stderr |     result = await self.call_function(
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
2024-11-22 16:45:15 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
2024-11-22 16:45:15 | ERROR | stderr |     return await iterator.__anext__()
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
2024-11-22 16:45:15 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-11-22 16:45:15 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024-11-22 16:45:15 | ERROR | stderr |     return await future
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024-11-22 16:45:15 | ERROR | stderr |     result = context.run(func, *args)
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/anaconda3/envs/llava_plus/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
2024-11-22 16:45:15 | ERROR | stderr |     return next(iterator)
2024-11-22 16:45:15 | ERROR | stderr |   File "/mnt/petrelfs/songmingyang/code/reasoning/tool-agent/LLaVA-Plus-Codebase/llava/serve/gradio_web_server_llava_plus.py", line 468, in http_bot
2024-11-22 16:45:15 | ERROR | stderr |     if data["error_code"] == 0:
2024-11-22 16:45:15 | ERROR | stderr | KeyError: 'error_code'
